# .github/workflows/fetch.yml

name: Merge upstream branches
on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'Grey-Wind'
          git config --global user.email '1953438158@qq.com'
          git config --global credential.helper store
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/QingYi-Studio/assets.git tmp
          cd tmp
          git remote add upstream https://${{ secrets.PAT_TOKEN }}@github.com/Grey-Wind/assets.git
          git fetch upstream
          git merge upstream/master
          git push origin master  
        
#secrets.PAT_TOKEN
#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